version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch-in-action-7.15.1
    environment:
      - node.name=node1
      - cluster.name=elasticsearch-in-action
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch-in-action
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana-7.15.1
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elasticsearch-in-action
    depends_on: 
      - elasticsearch

volumes:
  node1-data:
    driver: local

networks:
  elasticsearch-in-action:
